/* boocore_words_packs.js (GLOBAL VERSION)
   This exposes word packs on window.BOOCoreWords
*/

window.BOOCoreWords = {
  CORE_WORDS: [
    "WATCH","WATCHING","WATCHER","THE WATCHER WAITS",
    "LISTEN","WAIT","HERE","HE IS HERE","IT IS HERE","THEY ARE HERE",
    "PRESENCE","PRESENCE IN ROOM","PRESENCE IN HALL",
    "NEAR","BEHIND","ONE BEHIND YOU",
    "SILENT","SILENCE","SILENCE IN ROOM","SILENCE IN HALL",
    "OPEN","CLOSED","LOCKED","UNLOCKED",
    "LOOK","LOOK AT ME","MOVE","TURN"
  ],

  PLACES: [
    "CELLAR","BASEMENT","STAIRS","UP","UPSTAIRS","BELOW","ABOVE",
    "HALL","CORRIDOR","PASSAGE","DOOR","DOORWAY","ROOM","CHAMBER",
    "WINDOW","FLOOR","WALL","HANDS ON WALL",
    "CRYPT","TOMB","OSSUARY","SEPULCHER","CATACOMB",
    "GRAVE","GRAVEYARD","CEMETERY",
    "CHAPEL","CHURCH","CATHEDRAL","ALTAR","SHRINE","SANCTUM",
    "CLOISTER","MONASTERY","ABBEY",
    "RUINS","STONE","MIRROR","GATE","THRESHOLD"
  ],

  ENTITIES: [
    "GHOST","SPIRIT","ENTITY",
    "PHANTOM","PHANTASM","SPECTER","APPARITION",
    "GHOUL","WIGHT",
    "DEMON",
    "CRYPTID"
  ],

  ACTIONS_DIRECTIVES: [
    "STOP","NO","GO","BACK","LEAVE THIS PLACE","DO NOT ENTER",
    "DON'T SAY THAT","NOT YOUR TIME","CANNOT ESCAPE FATE",
    "COME","STAY","LEFT","RIGHT","FORWARD","BELOW","ABOVE"
  ],

  TONE_TRAITS: [
    "COLD","FREEZING","WARM","HOT",
    "DREAD","OMINOUS","EERIE","SPOOKY","CREEPY","UNCANNY",
    "ANGRY","LONELY","MOURNFUL","SAD","FRIGHTENED","SCARED",
    "DARK","GLOOM","SHADOW","EYES IN DARK","WHISPER","WHISPERS IN DARK",
    "DARKNESS WILL FALL"
  ],

  PHRASES_MANIFESTATIONS: [
    "KNOCK","KNOCK ON DOOR",
    "FOOTSTEPS BEHIND YOU",
    "FIGURE AT WINDOW",
    "VOICE","VOICE IN MIRROR",
    "SCREAM","SCREAMS IN CELLAR",
    "I HEAR YOU","TALK TO ME","WHO ARE YOU","I SEE YOU","YOU SEE ME",
    "I WAS HERE","I TOLD YOU"
  ],

  HARD_STOP: [
    "STOP","NO","LEAVE THIS PLACE","DO NOT ENTER",
    "DON'T SAY THAT","NOT YOUR TIME","CANNOT ESCAPE FATE"
  ],

  // Optional packs (keep off unless you want them)
  NAMES_PROBABLE: [],
  COLORS_APPEARANCE: [],
  NUMBERS: [],
  SINGLE_LETTERS: []
};
